//------------------------------------------------------------------------------
// <auto-generated
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Battery
    {
        public Battery()
        {
            this.BatteryDets = new HashSet<BatteryDet>();
        }
    
        public int MethID { get; set; }
        public string BatteryName { get; set; }
        public string BatteryDesc { get; set; }
        public int OldBatteryID { get; set; }
        [Key]
        public int BatteryID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual ICollection<BatteryDet> BatteryDets { get; set; }
    }
}
