//------------------------------------------------------------------------------
// <auto-generated
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BatteryDet
    {
        public int BatteryID { get; set; }
        public int MethParaID { get; set; }
        public int OldBatteryDetID { get; set; }
        [Key]
        public int BatteryDetID { get; set; }
    
        public virtual Battery Battery { get; set; }
    }
}
