//------------------------------------------------------------------------------
// <auto-generated
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CannedComment
    {
        [Key]
        public int CannedCommentID { get; set; }
        public int CommentTypeID { get; set; }
        public string CommentShort { get; set; }
        public string Comment { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
