//------------------------------------------------------------------------------
// <auto-generated
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Comment
    {
        public System.DateTime CommentDate { get; set; }
        public short Commentor { get; set; }
        public short CommentTypeID { get; set; }
        public int ItemID { get; set; }
        public string Comment1 { get; set; }
        public string CommentShort { get; set; }
        public bool RepNote { get; set; }
        public int OldCommentID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public bool CustAlert { get; set; }
        public bool WO_Alert { get; set; }
        public bool WIP_Alert { get; set; }
        public bool SampAlert { get; set; }
        public bool ProdAlert { get; set; }
        public bool TestAlert { get; set; }
        [Key]
        public int CommentID { get; set; }
        public int WO_ID { get; set; }
    }
}
