//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contact : Entity<Contact>
    {

        public Contact()
        {
           //this.Customer = new HashSet<Customer>();
        }

        public int? CustID { get; set; }
        public int? AddressID { get; set; }
        public string Prefix { get; set; }
        public string FName { get; set; }
        public string MI { get; set; }
        public string LName { get; set; }
        public string Suffix { get; set; }
        public string Title { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string PW { get; set; }
        public bool IsTempPW { get; set; }
        public bool PortalUser { get; set; }
        public bool RepRecip { get; set; }
        public bool ReceiptConfRecip { get; set; }
        public int? OldContactID { get; set; }
        [Key]
        public int? ContactID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual Customer Customer { get; set; }

    }
}
