//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer : Entity<Customer>
    {
        public Customer()
        {
            //this.Contact = new HashSet<Contact>();
            //this.CustAddrs = new HashSet<CustAddr>();
            //this.WorkOrders = new HashSet<WorkOrder>();
            //this.WorkOrderArchives = new HashSet<WorkOrderArchive>();
            //this.Products = new HashSet<Product>();
        }
    
        public string CustShortName { get; set; }
        public string CustLongName { get; set; }
        public string PWSID { get; set; }
        public bool Active { get; set; }
        public bool Special { get; set; }
        public string SpecialDesc { get; set; }
        public string AccntNum { get; set; }
        public int PriContID { get; set; }
        public int PriAddrID { get; set; }
        public int OldCustID { get; set; }
        public string Region { get; set; }
        public int CustCatID { get; set; }
        [Key]
        public int CustID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        //public virtual ICollection<Contact> Contact { get; set; }
        //public virtual ICollection<CustAddr> CustAddrs { get; set; }
        //public virtual ICollection<WorkOrder> WorkOrders { get; set; }
        //public virtual ICollection<WorkOrderArchive> WorkOrderArchives { get; set; }
        //public virtual ICollection<Product> Products { get; set; }
    }
}
