//------------------------------------------------------------------------------
// <auto-generated
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ErrLog
    {
        public string TimeStamp { get; set; }
        public int ErrNum { get; set; }
        public string ErrDesc { get; set; }
        public string ModName { get; set; }
        public string ProcName { get; set; }
        public int LineNum { get; set; }
        public string UserName { get; set; }
        public string CompName { get; set; }
        public string AppVer { get; set; }
        public string Note { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        [Key]
        public int ErrorID { get; set; }
    }
}
