//------------------------------------------------------------------------------
// <auto-generated
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class InstrDataStaging
    {
        [Key]
        public int InstrDataID { get; set; }
        public int LIMS_InstrID { get; set; }
        public int LIMS_AnalystID { get; set; }
        public System.DateTime ImportDate { get; set; }
        public int LIMS_BatchID { get; set; }
        public string InstrRepDesig { get; set; }
        public int LIMS_RepID { get; set; }
        public System.DateTime AnalysisDate { get; set; }
        public System.DateTime AnalysisTime { get; set; }
        public string InstrParaDesig { get; set; }
        public short LIMS_ParaID { get; set; }
        public short MassNo { get; set; }
        public double Result { get; set; }
        public string InstrUnitsDesig { get; set; }
        public short LIMS_UnitsID { get; set; }
        public bool ProcessResult { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
