//------------------------------------------------------------------------------
// <auto-generated
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Matrix
    {
        public string MatrixName { get; set; }
        public string MatrixAbbr { get; set; }
        public short SortOrder { get; set; }
        public string DenominatorDesig { get; set; }
        public short MatrixPhase { get; set; }
        public int OldMatrixID { get; set; }
        [Key]
        public int MatrixID { get; set; }
    }
}
