//------------------------------------------------------------------------------
// <auto-generated
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MethPara
    {
        public int MethID { get; set; }
        public int ParaID { get; set; }
        public int UnitsID_Solid { get; set; }
        public int UnitsID_Liquid { get; set; }
        public short RoundMeth { get; set; }
        public short NumDigits { get; set; }
        public short? SortOrder { get; set; }
        public float PQL_Solid { get; set; }
        public float PQL_Liquid { get; set; }
        public int? OldMethParaID { get; set; }
        [Key]
        public int MethParaID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }

        public Para Para { get; set; }
    }
}
