//------------------------------------------------------------------------------
// <auto-generated
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Meth
    {
        public string MethName { get; set; }
        public string MethDesc { get; set; }
        public int NumRep { get; set; }
        public bool Default { get; set; }
        public bool NoMethSelected { get; set; }
        public int OldMethID { get; set; }
        [Key]
        public int MethID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
