//------------------------------------------------------------------------------
// <auto-generated
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Para
    {
        public string ParaShort { get; set; }
        public string ParaLong { get; set; }
        public string ParaDesc { get; set; }
        public int? OldParaID { get; set; }
        public bool ReducedPQL { get; set; }
        public int? PriMassNo { get; set; }
        [Key]
        public int ParaID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
