//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Model
{
    using Model;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product: Entity<Product>
    {
        public int CustID { get; set; }
        public string ProdName { get; set; }
        public string ProdDesc { get; set; }
        public int UnitsTypeID { get; set; }
        public bool Active { get; set; }
        public int? OldProdID { get; set; }
        [Key]
        public int ProdID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
       // public virtual Customer Customer { get; set; }
    }
}
