//------------------------------------------------------------------------------
// <auto-generated
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Report : Entity<Report>
    {
        public Report()
        {
            //  this.Sample = new HashSet<Sample>();
            this.RepResults = new HashSet<RepResult>();
        }
        [Key]
        public int ReportID { get; set; }
        public string ReportNum { get; set; }
        public int WO_ID { get; set; }
        public int OldReportID { get; set; }
        
        public bool Signed { get; set; }
        public bool Sent { get; set; }
        public System.Guid RowID { get; set; }
        [Column("Report")]
        public byte[] ReportFile { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        [NotMapped]
        public string ReportType { get; set; }
        [NotMapped]
        public virtual ICollection<RepResult> RepResults { get; set; }
        // public virtual ICollection<Sample> Sample { get; set; }
        // public virtual WorkOrder WorkOrder { get; set; }

    }
}
