//------------------------------------------------------------------------------
// <auto-generated
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ReportArchive : Entity<ReportArchive>
    {
        public ReportArchive()
        {
            //this.RR_ReportArchive = new HashSet<RR_ReportArchive>();
            this.RepResults = new HashSet<RepResultArchive>();
        }
        [Key]
        public int ReportID { get; set; }
        public string ReportNum { get; set; }
        public int WO_ID { get; set; }
        public int? OldReportID { get; set; }

        public bool Signed { get; set; }
        public bool Sent { get; set; }
        public System.Guid RowID { get; set; }
        public byte[] Report { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        [NotMapped]
        public virtual ICollection<RepResultArchive> RepResults { get; set; }
    }
}
