//------------------------------------------------------------------------------
// <auto-generated
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RR_ReportArchive : Entity<RR_ReportArchive>
    {
        [Key]
        public int RR_ReportID { get; set; }
        public int RR_ID { get; set; }
        public int ReportID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public int SampID { get; set; }
        public virtual ReportArchive Report { get; set; }
        // public virtual Sample Sample { get; set; }
        public virtual RepResultArchive RepResult { get; set; }
        
       
    }
}
