//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class SampleArchive : Entity<SampleArchive>
    {
        public SampleArchive()
        {
            //this.ReplicateArchives = new HashSet<ReplicateArchive>();
            //this.SampMethParaArchives = new HashSet<SampMethParaArchive>();
            //this.SampSpecArchives = new HashSet<SampSpecArchive>();
            this.Reportnews = new HashSet<Report>();
            this.RR_Reports = new HashSet<RR_ReportArchive>();

        }

        public int WO_ID { get; set; }
        public string SampNum { get; set; }
        public System.DateTime? SampCollectionDate { get; set; }
        public System.DateTime SampDate { get; set; }
        public System.DateTime? TimeCollected { get; set; }
        public string LotNum { get; set; }
        public string SubLotNum { get; set; }
        public int? ProdID { get; set; }
        public string RepSampDesc { get; set; }
        public string Description { get; set; }
        public int StatusID { get; set; }
        public System.DateTime? PresDate { get; set; }
        public System.DateTime? PresTime { get; set; }
        public bool AcidifiedUponReceipt { get; set; }
        public int? AcidifiedBy { get; set; }
        public bool DEP_Reportable { get; set; }
        public string PWS_ID { get; set; }
        public short? Turbid { get; set; }
        public int? TurbidCheckBy { get; set; }
        public System.DateTime? TurbidCheckDate { get; set; }
        public System.DateTime? TurbidCheckTime { get; set; }
        public int LoggedBy { get; set; }
        public short? NumUnits { get; set; }
        public float? UnitWt { get; set; }
        public float? DoseWt { get; set; }
        public bool? DetUnitWt { get; set; }
        public short? NumUnitsWeighed { get; set; }
        public float? TotUnitsWt { get; set; }
        public int? TotUnitsWtMeasBy { get; set; }
        public System.DateTime? TotUnitsWtMeasDate { get; set; }
        public int? OldSampID { get; set; }
        [Key]
        public int SampID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }

        public virtual Product Product { get; set; }

        public virtual ICollection<RR_ReportArchive> RR_Reports { get; set; }
        [NotMapped]
        public virtual ICollection<Report> Reportnews { get; set; }
        public virtual WorkOrderArchive WorkOrder { get; set; }
    }
}
