//------------------------------------------------------------------------------
// <auto-generated
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SampMethPara
    {
        public int SampID { get; set; }
        public float AvgRes { get; set; }
        public int SD { get; set; }
        public int DE_UnitsID { get; set; }
        public int RepUnitsID { get; set; }
        public int MethID { get; set; }
        public int ParaID { get; set; }
        public int RoundMeth { get; set; }
        public int NumDigits { get; set; }
        public int StatusID { get; set; }
        public bool CustReq { get; set; }
        public float PQL { get; set; }
        public int? OldSampMethParaID { get; set; }
        [Key]
        public int SampMethParaID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Para Para { get; set; }
    }
}
