//------------------------------------------------------------------------------
// <auto-generated
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Spec
    {
        public int ParaID { get; set; }
        public float Limit { get; set; }
        public string Operator { get; set; }
        public int UnitsID { get; set; }
        [Key]
        public int SpecID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
