//------------------------------------------------------------------------------
// <auto-generated
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SpecGroup
    {
        public SpecGroup()
        {
            this.SpecGroupDets = new HashSet<SpecGroupDet>();
        }
    
        public string SpecGroupName { get; set; }
        public int CustID { get; set; }
        public int ProdID { get; set; }
        public int OldSpecGroupID { get; set; }
        [Key]
        public int SpecGroupID { get; set; }
    
        public virtual ICollection<SpecGroupDet> SpecGroupDets { get; set; }
    }
}
