//------------------------------------------------------------------------------
// <auto-generated
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Status
    {
        [Key]
        public int StatusID { get; set; }
        public string StatDesc { get; set; }
        public bool WO { get; set; }
        public bool Samp { get; set; }
        public bool Rep { get; set; }
        public bool Result { get; set; }
        public bool Batch { get; set; }
        public bool SampProtPara { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
