//------------------------------------------------------------------------------
// <auto-generated
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TAT
    {
        [Key]
        public int TAT_ID { get; set; }
        public string TAT_ShortDesc { get; set; }
        public string TAT_LongDesc { get; set; }
        public short SortOrder { get; set; }
        public int Days { get; set; }
        public bool BusinessDays { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
