//------------------------------------------------------------------------------
// <auto-generated
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblTablePermission
    {
        [Key]
        public int TableID { get; set; }
        public string TABLE_NAME { get; set; }
        public string ACCESS_NAME { get; set; }
        public bool DontLink { get; set; }
        public string TABLE_SCHEMA { get; set; }
        public bool UpdateEmployee { get; set; }
        public bool DeleteEmployee { get; set; }
        public bool InsertEmployee { get; set; }
        public bool SelectClient { get; set; }
        public bool InsertClient { get; set; }
        public bool DeleteClient { get; set; }
        public bool UpdateClient { get; set; }
    }
}
