//------------------------------------------------------------------------------
// <auto-generated
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Unit
    {
        public string UnitsDesignation { get; set; }
        public string UnitsDesc { get; set; }
        public int UnitsTypeID { get; set; }
        public bool Base { get; set; }
        public double ConvToBase { get; set; }
        public int ReqNormUnitID { get; set; }
        public string Numerator { get; set; }
        public int OldUnitsID { get; set; }
        [Key]
        public int UnitsID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
