//------------------------------------------------------------------------------
// <auto-generated
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public string Logon { get; set; }
        public string UserName { get; set; }
        public string UserInitials { get; set; }
        public int DeptID { get; set; }
        public string Title { get; set; }
        public string PW { get; set; }
        public int SG_ID { get; set; }
        public bool Active { get; set; }
        public int OldUserID { get; set; }
        [Key]
        public int UserID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
